### PR TITLE
bump to API v60.0

### PR DESCRIPTION
**Pull request by kalena**
# Critical Changes

# Changes

- Updated files to API v60.0
- NOTE: This PR includes changes from [PR #23](https://github.com/SFDO-Community/sticky-selectron/pull/23) to bump devDependencies

# Issues Closed

### CODE REVIEW

**Comment by kalena** [comment]
@pickettd cumulusci.yml - downgrade minimum_cumulusci_version from 3.86.0 to 3.75.1 due to GitHub runner problem.

**Review by pickettd — APPROVED** [review]
API and style changes look like they will work. Thanks again @kalena !

**Comment by pickettd** [comment]
I added @coriobriensfdo as an assignee to review the API version bump and whitespace formatting changes in the cumulus config file.

**Review by coriobriensfdo — APPROVED** [review]

**Comment by coriobriensfdo** [comment]
@pickettd done, sorry I've been OOO sick.

**Pull request merged**
